Remove deprecated has_rdoc
Installing using Ruby 3.4.2 is failing to bundle due to deprecated has_rdoc in this gem.

After 9 years without touching it, here we go.

Failure:

Invalid gemspec in [/gems/ruby/3.4.0/bundler/gems/pdf-reader-b7ec47449fcd/pdf-reader.gemspec]: undefined method 'has_rdoc=' for an instance of Gem::Specification
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method 'name' for nil
  /usr/local/lib/ruby/site_ruby/3.4.0/rubygems/stub_specification.rb:154:in 'Gem::StubSpecification#name'
          /gems/ruby/3.4.0/gems/bundler-2.7.1/lib/bundler/stub_specification.rb:7:in 'Bundler::StubSpecification.from_stub'
          /gems/ruby/3.4.0/gems/bundler-2.7.1/lib/bundler/source/git.rb:431:in 'block in Bundler::Source::Git#load_gemspec'
          /gems/ruby/3.4.0/gems/bundler-2.7.1/lib/bundler/shared_helpers.rb:54:in 'Dir.chdir'
          /gems/ruby/3.4.0/gems/bundler-2.7.1/lib/bundler/shared_helpers.rb:54:in 'block in Bundler::SharedHelpers#chdir'
          /gems/ruby/3.4.0/gems/bundler-2.7.1/lib/bundler/shared_helpers.rb:53:in 'Monitor#synchronize'
          /gems/ruby/3.4.0/gems/bundler-2.7.1/lib/bundler/shared_helpers.rb:53:in 'Bundler::SharedHelpers#chdir'
          /gems/ruby/3.4.0/gems/bundler-2.7.1/lib/bundler/source/git.rb:428:in 'Bundler::Source::Git#load_gemspec'